import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./ui/nav-bar";
import { inter } from "./ui/fonts";
import { auth } from "@/auth"; // 서버 세션 가져오기
import { SessionProvider } from "next-auth/react"; // 바로 import

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 1. 서버에서 세션 가져오기
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <SessionProvider session={session}>
          <div className="flex flex-col bg-base-100">
            <div className="w-full">
              <Navbar />
            </div>
            <div className="grow">{children}</div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}