import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./ui/nav-bar";
import { inter } from "./ui/fonts";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <div className="flex flex-col bg-base-100">
            <div className="w-full"><Navbar/></div>
            <div className="grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
 